server:
  port: 8080
spring:
  application:
    name: rabbitMq
  profiles:
    active: test
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
  redis:
    database: 7
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 10000ms
    jedis:
      pool:
        max-active: 1000
        max-idle: 10
        max-wait: -1
        min-idle: 5
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password:
    #开启confirm模式
    publisher-confirm-type: correlated
    #开启发送失败返回
    publisher-returns: true
swagger:
  enable: true
knife4j:
  enable: true